lacework/terraform-provider-lacework

CHANGELOG.md
Thus PR updates the `CHANGELOG.md` to reflect the current state of the project. 
=> doc(CHANGELOG): add resources and importer

website/docs/index.html.markdown, website/lacework.erb
=> feat(website): add index and main layout

website/docs/d/api_token.html.markdown, website/docs/index.html.markdown, website/docs/r/integration_aws_cfg.html.markdown, website/docs/r/integration_aws_ct.html.markdown, website/docs/r/integration_azure_al.html.markdown, website/docs/r/integration_azure_cfg.html.markdown, website/docs/r/integration_gcp_at.html.markdown, website/docs/r/integration_gcp_cfg.html.markdown, website/lacework.erb
Built it using their terraform website repo: https://github.com/hashicorp/terraform-website
=> feat(website): Add documentation for every resource available

scripts/release.sh
=> ci: add date to CHANGELOG.md

scripts/release.sh
=> ci: zip binaries without bin/

.circleci/config.yml, GNUmakefile, go.mod, scripts/release.sh
=> build: upgrade Go version to 1.15

.circleci/config.yml, website/docs/r/integration_gcp_at.html.markdown, website/docs/r/integration_gcp_cfg.html.markdown
=> ci: send slack notifications to team alias ⭐

examples/resource_lacework_alert_channel_gcp_pub_sub/main.tf, lacework/resource_lacework_alert_channel_gcp_pub_sub.go, lacework/resource_lacework_alert_channel_gcp_pub_sub_test.go, website/docs/r/alert_channel_gcp_pub_sub.html.markdown
Add the previously omitted issue_grouping field to gcp pub sub resource
=> fix: Add issue_grouping field to gcp pub sub

lacework/resource_lacework_alert_channel_service_now.go
=> fix: Correct mapping for Snow instance_url

website/docs/r/integration_gcr.html.markdown
=> doc: create service accounts for GCR integration

.circleci/config.yml, scripts/release.sh
=> ci: delete 'master' branch

website/docs/r/integration_aws_ct.html.markdown
=> docs(website): add missing retries argument

website/docs/r/integration_ecr.html.markdown
=> docs(website): fix ECR Module example

go.mod, go.sum, vendor/modules.txt
=> ci: fix prepare-release job

go.sum
=> ci: fix dependencies

GNUmakefile
=> ci: clean left over files during integration test

scripts/release.sh
=> ci: sign lacework-releng commits

go.sum
=> chore: fixed deps by running make go-vendor

go.sum
Just ran:
```
make go-vendor
```
=> chore: fix Go deps

go.mod, go.sum, lacework/provider.go, vendor/github.com/lacework/go-sdk/api/account.go, vendor/github.com/lacework/go-sdk/api/user_profile.go, vendor/github.com/lacework/go-sdk/lwdomain/README.md, vendor/github.com/lacework/go-sdk/lwdomain/domain.go, vendor/modules.txt
JIRA: https://lacework.atlassian.net/browse/ALLY-632
=> feat: gracefully handle account config <ACCOUNT>.lacework.net

website/docs/r/integration_ghcr.html.markdown, website/docs/r/resource_group_aws.html.markdown, website/docs/r/resource_group_azure.html.markdown, website/docs/r/resource_group_gcp.html.markdown
=> docs: fix html markdown indentation

website/docs/r/resource_group_aws.html.markdown, website/docs/r/resource_group_gcp.html.markdown
=> docs: standardize mention of 'ids'

integration/integration.go
=> test: fix integration tests

go.sum
=> ci: fix release pipeline by running make prepare

go.sum
=> ci: fix release pipeline

website/docs/r/alert_channel_webhook.html.markdown
=> docs: fix webhook alert channel example

website/docs/r/alert_rule.html.markdown
Fix incorrect summary on alert rule tf registry page.
=> docs: Fix alert rule doc summary

.golangci.yaml, integration/integration.go, integration/resource_lacework_alert_channel_aws_s3_test.go, lacework/casting.go, lacework/resource_lacework_agent_access_token.go, lacework/resource_lacework_alert_channel_webhook.go, lacework/resource_lacework_integration_aws_cfg.go, lacework/resource_lacework_integration_aws_ct.go, lacework/resource_lacework_integration_aws_govcloud_cfg.go, lacework/resource_lacework_integration_aws_govcloud_ct.go, lacework/resource_lacework_integration_azure_al.go, lacework/resource_lacework_integration_azure_cfg.go, lacework/resource_lacework_integration_gcp_at.go, lacework/resource_lacework_integration_gcp_cfg.go, lacework/resource_lacework_integration_gcr.go
***Issue***: https://lacework.atlassian.net/browse/ALLY-657
Fix Linting issues
*** Notes ***
Codefresh pipeline terraform-provider-lacework/test-build updated with `make lint` command
=> style: Fix linting

examples/resource_lacework_alert_rule/main.tf, lacework/resource_lacework_alert_rule.go, website/docs/r/alert_rule.html.markdown
=> fix: Deprecate channels attribute in favour of alert_channels

website/docs/index.html.markdown
=> docs: Add environment variables for Windows

examples/resource_lacework_alert_rule/main.tf, integration/resource_lacework_alert_rule_test.go
=> test: fix alert-rule tests

integration/resource_lacework_alert_rule_test.go, integration/resource_lacework_report_rule_test.go
disable failing alert rule tests
=> test: disable failing alert rule tests

integration/integration.go, integration/resource_lacework_alert_channel_aws_cloudwatch_test.go, integration/resource_lacework_alert_channel_aws_s3_test.go, integration/resource_lacework_alert_channel_cisco_webex_test.go, integration/resource_lacework_alert_channel_datadog_test.go, integration/resource_lacework_alert_channel_email_test.go, integration/resource_lacework_alert_channel_gcp_pub_sub_test.go, integration/resource_lacework_alert_channel_jira_cloud_test.go, integration/resource_lacework_alert_channel_jira_server_test.go, integration/resource_lacework_alert_channel_microsoft_teams_test.go, integration/resource_lacework_alert_channel_slack_test.go, integration/resource_lacework_alert_channel_webhook_test.go, integration/resource_lacework_integration_victorops_test.go
Use v2 endpoints in integration tests
=> test: Use v2 endpoints in tests

examples/resource_lacework_vulnerability_exception_container/main.tf, examples/resource_lacework_vulnerability_exception_host/main.tf, go.mod, go.sum, lacework/resource_lacework_vulnerability_exception_container.go, lacework/resource_lacework_vulnerability_exception_host.go, vendor/github.com/lacework/go-sdk/api/container_registries_ghcr.go, vendor/github.com/lacework/go-sdk/api/integrations_ctr_reg.go, vendor/github.com/lacework/go-sdk/api/integrations_ctr_reg_ecr_access_key.go, vendor/github.com/lacework/go-sdk/api/vulnerability_exceptions.go, vendor/modules.txt, website/docs/r/vulnerability_exception_container.html.markdown, website/docs/r/vulnerability_exception_host.html.markdown
Remove `expiration_time` field from the terraform-provider
=> refactor: remove expiration time

.github/pull_request_template.md
=> docs: fix PR template document

integration/resource_lacework_team_member_test.go
***Issue***: [Include link to the Jira/Github Issue](https://lacework.atlassian.net/browse/ALLY-856)
use lwdomain to separate account name from full domain in team_member test
=> test(team_member): use lwdomain to get correct account name

lacework/resource_lacework_policy.go, website/docs/r/policy.html.markdown, website/docs/r/query.html.markdown
Update policy documentation to show a query resource being created and used for a policy resource.
=> docs: update query and policy resources

website/docs/r/query.html.markdown
=> docs: fix typo

website/docs/index.html.markdown, website/docs/r/integration_aws_ct.html.markdown, website/docs/r/integration_azure_cfg.html.markdown, website/docs/r/integration_ecr.html.markdown, website/docs/r/policy.html.markdown, website/docs/r/query.html.markdown, website/docs/r/vulnerability_exception_container.html.markdown, website/docs/r/vulnerability_exception_host.html.markdown
=> chore: deprecate CLI Wiki

GNUmakefile
=> ci: add make cmd for output go tests in junit format

website/docs/r/integration_aws_eks_audit_log.html.markdown
Fixes some issues with the aws eks audit log docs
=> fix(docs): Fix aws eks audit log docs

integration/resource_lacework_policy_test.go
Check assertion ignoring order of slices
=> test: fix policy test

examples/resource_lacework_vulnerability_exception_container/main.tf, examples/resource_lacework_vulnerability_exception_host/main.tf, integration/resource_lacework_vulnerability_exception_host_test.go, lacework/resource_lacework_vulnerability_exception_container.go, lacework/resource_lacework_vulnerability_exception_container_test.go, lacework/resource_lacework_vulnerability_exception_host.go, lacework/schema_validators.go, vendor/github.com/lacework/go-sdk/api/cloud_accounts_aws_eks_audit.go, vendor/github.com/lacework/go-sdk/api/vulnerability_exceptions.go, website/docs/r/vulnerability_exception_container.html.markdown, website/docs/r/vulnerability_exception_host.html.markdown
***Issue***: 
https://lacework.atlassian.net/browse/ALLY-1001
Add expiry field to vulnerability exception host and container resources.
=> feat: add expiry field for Vulnerability Exceptions

integration/resource_lacework_policy_test.go
***Issue***:
https://lacework.atlassian.net/browse/ALLY-1050
Invalid policy type in integration testing for policy resource
=> test(policy): fix policy type in integration testing

lacework/errors.go, lacework/errors_test.go
***Issue***: 
https://lacework.atlassian.net/browse/ALLY-1053
=> fix: handle resource deleted outside of terraform scope

lacework/resource_lacework_policy.go, website/docs/r/policy.html.markdown
https://lacework.atlassian.net/browse/RAIN-33379
Summary is not a valid policy type.
=> fix(RAIN-33379): Fix documentation of policy types

lacework/resource_lacework_integration_azure_al.go
***Issue***:
https://lacework.atlassian.net/browse/ALLY-1134
migrate resource_lacework_integration_azure_al to use v2 api
=> refactor: migrate resource_lacework_integration_azure_al to use v2 api

lacework/resource_lacework_integration_azure_cfg.go
azure_cfg resource is sending incorrect cloud account type
=> fix: azure_cfg resource sending incorrect cloud account type

integration/resource_lacework_alert_rule_test.go, lacework/casting.go, lacework/resource_lacework_alert_rule.go
***Issue***: https://lacework.atlassian.net/browse/ALLY-1219
Add new event category type `K8sActivity` to alert_rule resource 
***How was it tested***
run `TestAlertRuleCategories`
=> feat: add event category type 'K8sActivity' to alert_rule resource

examples/resource_lacework_integration_gcp_agentless_scanning/main.tf, integration/integration.go, integration/resource_lacework_integration_gcp_agentless_scanning_test.go, lacework/provider.go, lacework/resource_lacework_integration_gcp_agentless_scanning.go, website/docs/r/integration_gcp_agentless_scanning.html.markdown
***Issue***: RAIN-43475
This features adds Lacework terraform provider module changes to handle GCP Sidekick Integration.
Added integration test and html docs to show usage.
=> feat(api) Adds GCP Sidekick Integration support

lacework/resource_lacework_integration_ecr.go
***Issue***: 
https://lacework.atlassian.net/browse/ALLY-1305
fix upgrade issue with limit_by_labels
=> fix: upgrade issue with limit_by_labels

examples/resource_lacework_alert_channel_jira_cloud/main.tf, examples/resource_lacework_alert_channel_jira_server/main.tf, integration/resource_lacework_alert_channel_jira_cloud_test.go, integration/resource_lacework_alert_channel_jira_server_test.go, lacework/resource_lacework_alert_channel_jira_cloud.go, lacework/resource_lacework_alert_channel_jira_cloud_test.go, lacework/resource_lacework_alert_channel_jira_server.go, lacework/resource_lacework_alert_channel_jira_server_test.go, website/docs/r/alert_channel_jira_cloud.html.markdown, website/docs/r/alert_channel_jira_server.html.markdown
***Issue***:
https://lacework.atlassian.net/browse/ALLY-1220
This adds the bidirectional `configuration` option to the Lacework terraform provider
=> feat(jira): add bidirectional configuration 

examples/resource_lacework_policy_exception/main.tf, integration/resource_lacework_policy_exception_test.go
***Issue***: https://lacework.atlassian.net/browse/GROW-1210
Add new integration test for invalid policy constraints
=> test: add new integration test for invalid policy exception constraints

integration/resource_lacework_integration_gcp_gke_audit_log_test.go
=> ci: set gcp private key to env var

examples/resource_lacework_policy_compliance/main.tf, integration/resource_lacework_policy_compliance_test.go, lacework/provider.go, lacework/resource_lacework_policy_compliance.go, website/docs/r/policy.html.markdown, website/docs/r/policy_compliance.html.markdown
***Issue***: https://lacework.atlassian.net/browse/GROW-1659
Add new resource `resource_lacework_policy_compliance` to support the `Compliance` policy type
Run `make integration-test regex=TestPolicyComplianceCreate` to test.
=> feat(resource): add support for compliance policies

lacework/resource_lacework_managed_policies.go
Slack thread:
https://lacework.slack.com/archives/C04CYEQ3W3G/p1690903559347099?thread_ts=1690866622.916049&cid=C04CYEQ3W3G
Run `make lint`
=> fix: lint error in resource_lacework_managed_policies.go

website/docs/r/resource_group.html.markdown
The current doc link points to RGv1 docs instead of RGv2.
=> docs: Update RG doc link to RGv2 version

website/docs/r/resource_group.html.markdown
Adding a description to the Terraform code sample for creating resource groups v2. 
I'm also changing the operator of the main group to what _I think_ it's meant to be... please check me on this.
=> Docs: Adding example introductory paragraph

docs/resources/policy.md, docs/resources/policy_compliance.md, lacework/resource_lacework_policy.go, lacework/resource_lacework_policy_compliance.go
***Issue***: #583 
API docs require a remediation string to be provided. 
Docs [link](https://yourlacework.lacework.net/api/v2/docs#tag/Policies/paths/~1api~1v2~1Policies/post)
=> fix: `remediation` is a required for policy & policy_compliance

vendor/github.com/lacework/go-sdk/api/cloud_accounts_azure_sidekick.go
***Issue***: n/a
Currently the main branch has a discrepancy in the vendor folder. Re-ran `go vendor` and raise this PR with the delta.
=> fix: missing files in vendor

docs/resources/resource_group_container.md
***Issue***: 
Closes https://github.com/lacework/terraform-provider-lacework/issues/602
Fixed broken link to documentation. 
=> docs: fixed resource groups broken link

integration/resource_lacework_policy_exception_test.go
Codefresh failure:
https://g.codefresh.io/build/659d1923df1107d2516cb9ab?step=Integration&tab=output&logs=terminal
TestPolicyExceptionInvalidConstraint failed due to the error message change in https://github.com/lacework/services/pull/18387/files#diff-4d159a775505a4026f5a01f03d33bc1a534aecb098169c95b386156e956f3419R174
=> fix: update error message in TestPolicyExceptionInvalidConstraint

lacework/data_source_lacework_metric_module.go
***Issue***:  https://lacework.atlassian.net/browse/GROW-2716
Add Terraform provider version to data collected by data source lacework_metric_module
=> chore: add provider version to lacework_metric_module

.github/workflows/nightly.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml, .github/workflows/test-build.yml, .github/workflows/verify-release.yml
***Issue***: 
https://lacework.atlassian.net/browse/GROW-2760
Provides workflows for testing and release to replace codefresh
=> ci: migrate from codefresh to github workflows

.github/CODEOWNERS
=> chore(GROW-2952): update codeowners

.github/workflows/test-build.yml
Revert this PR to re-enable resource group tests
=> Revert "chore: remove run-integration-tests to unblock release process

integration/resource_lacework_alert_rule_test.go
=> chore: Re-enable alert rule integration tests

examples/resource_lacework_integration_azure_agentless_scanning/main.tf, integration/resource_lacework_integration_azure_agentless_scanning_test.go
Enable azure agentless test after fixing the azure agentless example.
=> Fix: Enable azure agentless test

lacework/resource_lacework_resource_group.go
***Issue***: Include link to the Jira/Github Issue (REQUIRED)
https://lacework.atlassian.net/browse/LINK-3295
https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/data-consistency-errors#resolving-data-consistency-errors
=> fix: add Computed: True to resource_group enabled
