GNUmakefile, go.mod, go.sum, vendor/github.com/lacework/go-sdk/api/api.go, vendor/github.com/lacework/go-sdk/api/client.go, vendor/github.com/lacework/go-sdk/api/events.go, vendor/github.com/lacework/go-sdk/api/integrations.go, vendor/github.com/lacework/go-sdk/api/vulnerabilities.go, vendor/modules.txt
Remove the `GOPRIVATE` environment variable since the `go-sdk` is now....
Also, updated the go package dependency! 😉
=> chore(go): update lacework/go-sdk dependency

lacework/resource_lacework_integration_aws_cfg.go, lacework/resource_lacework_integration_aws_ct.go, lacework/resource_lacework_integration_azure_al.go, lacework/resource_lacework_integration_azure_cfg.go, lacework/resource_lacework_integration_gcp_at.go, lacework/resource_lacework_integration_gcp_cfg.go
When a user uses the Terraform Importer `terraform import resource.name ID`
the `Read()` function was not populating every field that the Lacework Server
returned, with this fix we are now updating all parameters in all integrations.
=> fix: import all parameters in all integration resources

lacework/data_source_lacework_api_token_test.go, lacework/provider_test.go, lacework/resource_lacework_integration_aws_ct_test.go
```
➜  terraform-provider-lacework git:(master) ✗ export TESTARGS="-run TestAccApiToken"
➜  terraform-provider-lacework git:(master) ✗ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccApiToken -timeout 120m
?   	github.com/lacework/terraform-provider-lacework	[no test files]
=== RUN   TestAccApiToken
--- PASS: TestAccApiToken (1.14s)
PASS
ok  	github.com/lacework/terraform-provider-lacework/lacework	1.438s
```
=> test: adds lacework_api_token acc tests

CHANGELOG.md
`CHANGELOG.md` version will be automatically updated to `0.1.0` by Hashi bot and needs to be set to `Unreleased` until then.
Signed-off-by: Scott Ford <scott.ford@lacework.net>
=> chore(version) Update CHANGELOG version from 0.1.0 to Unreleased

examples/data_source_lacework_agent_access_token/main.tf, lacework/data_source_lacework_agent_access_token.go, lacework/data_source_lacework_api_token.go, lacework/provider.go, scripts/release.sh, website/docs/d/agent_access_token.html.markdown, website/lacework.erb
To have parity with our resource `lacework_agent_access_token` we are
adding a new data source to retrieve Agent access tokens by looking up
for the Token Alias. (a.k.a Token Name)
```hcl
provider "lacework" {}
data "lacework_agent_access_token" "k8s" {
name = "k8s-deployments"
}
```
Contributes https://github.com/lacework/terraform-provider-lacework/issues/41
=> feat(data-source): new lacework_agent_access_token

website/docs/r/integration_gcp_at.html.markdown, website/docs/r/integration_gcp_cfg.html.markdown, website/docs/r/integration_gcr.html.markdown
A few documentation additions:
**JIRA: ALLY-256**
=> docs: adding more documentation about GCP resources

website/docs/r/integration_aws_ct.html.markdown
Closes https://github.com/lacework/terraform-provider-lacework/issues/59
=> docs: fix typo in aws_ct website resource

website/docs/r/alert_channel_aws_s3.html.markdown
This PR adds a missing curly brace in the code snippet for the S3 data export alert channel.
Signed-off-by: Scott Ford <scott.ford@lacework.net>
=> docs: fix closing curly brace in code snippet (S3 Data Export)

GNUmakefile, go.mod, go.sum, vendor/modules.txt
=> ci: pin Go tooling to specific versions

GNUmakefile
This will avoid pipeline failures like:
```
make clean-test
find . \( -name ".terraform*" -o -name "terraform.tfstate*" \) -exec rm -rf {} \;
find: ./examples/resource_lacework_alert_channel_datadog/.terraform: No such file or directory
find: ./examples/resource_lacework_alert_channel_email/.terraform: No such file or directory
make: *** [clean-test] Error 1
```
=> ci: make clean-test directive

examples/resource_lacework_alert_channel_datadog/main.tf, examples/resource_lacework_alert_channel_email/main.tf, go.sum, lacework/alert_channel.go, lacework/resource_lacework_alert_channel_aws_cloudwatch.go, lacework/resource_lacework_alert_channel_aws_s3.go, lacework/resource_lacework_alert_channel_cisco_webex.go, lacework/resource_lacework_alert_channel_datadog.go, lacework/resource_lacework_alert_channel_email.go, lacework/resource_lacework_alert_channel_gcp_pub_sub.go, lacework/resource_lacework_alert_channel_jira_cloud.go, lacework/resource_lacework_alert_channel_jira_server.go, lacework/resource_lacework_alert_channel_microsoft_teams.go, lacework/resource_lacework_alert_channel_newrelic.go, lacework/resource_lacework_alert_channel_pagerduty.go, lacework/resource_lacework_alert_channel_qradar.go, lacework/resource_lacework_alert_channel_service_now.go, lacework/resource_lacework_alert_channel_slack.go, lacework/resource_lacework_alert_channel_splunk.go, lacework/resource_lacework_alert_channel_victorops.go, lacework/resource_lacework_alert_channel_webhook.go, vendor/github.com/lacework/go-sdk/api/alert_channels.go
https://lacework.atlassian.net/browse/ALLY-331
*Example of adding Test Integration to TF Create of Alert Channels
Alert Channel resources run "Test Integration" `v2/AlertChannels/IntGuid/test` during Terraform Create.
The resource is deleted upon failing the Test.
Skip running the Test Integration with `test_integration` flag
```
resource "lacework_alert_channel_datadog" "example" {
name            = var.channel_name
...
test_integration    = true
}
```
=> feat: Run Test Alert Channel during TF Create

GNUmakefile, lacework/alert_channel.go, lacework/resource_lacework_alert_channel_aws_cloudwatch.go, lacework/resource_lacework_alert_channel_aws_s3.go, lacework/resource_lacework_alert_channel_cisco_webex.go, lacework/resource_lacework_alert_channel_datadog.go, lacework/resource_lacework_alert_channel_email.go, lacework/resource_lacework_alert_channel_gcp_pub_sub.go, lacework/resource_lacework_alert_channel_jira_cloud.go, lacework/resource_lacework_alert_channel_jira_server.go, lacework/resource_lacework_alert_channel_microsoft_teams.go, lacework/resource_lacework_alert_channel_newrelic.go, lacework/resource_lacework_alert_channel_pagerduty.go, lacework/resource_lacework_alert_channel_qradar.go, lacework/resource_lacework_alert_channel_service_now.go, lacework/resource_lacework_alert_channel_slack.go, lacework/resource_lacework_alert_channel_splunk.go, lacework/resource_lacework_alert_channel_victorops.go, lacework/resource_lacework_alert_channel_webhook.go
PR https://github.com/lacework/terraform-provider-lacework/pull/133 only tested alert channels after creation, but we need to test them
also when users modify them.
Corrected logging that always printed Datadog Integration.
=> refactor: test Alert Channels on create and modify

website/docs/index.html.markdown, website/docs/r/integration_aws_ct.html.markdown
Current documentation for Organization Level integration of Cloud
Accounts is not clear, this change is clarifying the need to define a
new Lacework provider with the argument `organization` set to `true`
to access the organization-level data set.
It also adds a clear example of how to migrate an existing AWS
CloudTrail integration from an account to the organization level.
Closes https://github.com/lacework/terraform-provider-lacework/issues/142
JIRA https://lacework.atlassian.net/browse/ALLY-611
=> docs: improve documentation for org account_mappings

examples/resource_lacework_resource_group_gcp/main.tf, examples/resource_lacework_resource_group_gcp/variables.tf, integration/integration.go, integration/resource_lacework_resource_group_gcp_test.go, lacework/provider.go, lacework/resource_lacework_resource_group_gcp.go, website/docs/r/resource_group_gcp.html.markdown, website/lacework.erb
Issue: https://lacework.atlassian.net/browse/ALLY-623
New Terraform resource for managing Gcp Resource Groups in Lacework
Usage:
``` hcl
resource "lacework_resource_group_gcp" "gcp" {
name        = "My Gcp Resource Group"
description = "This groups a subset of Gcp Accounts"
organization = "MyGcpOrg"
projects    = ["123456789", "234567891"]
}
```
Signed-off-by: Darren Murray darren.murray@lacework.net
=> feat(resource): New lacework_resource_group_gcp

examples/resource_lacework_resource_group_azure/main.tf, examples/resource_lacework_resource_group_azure/variables.tf, integration/integration.go, integration/resource_lacework_resource_group_azure_test.go, lacework/provider.go, lacework/resource_lacework_resource_group_azure.go, website/docs/r/resource_group_azure.html.markdown, website/lacework.erb
Issue: https://lacework.atlassian.net/browse/ALLY-624
New Terraform resource for managing Azure Resource Groups in Lacework
Usage:
``` hcl
resource "lacework_resource_group_azure" "azure" {
name        = "My Gcp Resource Group"
description   = "This groups a subset of Azure Subscriptions"
tenant        = "a11aa1ab-111a-11ab-a000-11aa1111a11a"
subscriptions = ["1a1a0b2-abc0-1ab1-1abc-1a000ab0a0a0", "2b000c3-ab10-1a01-1abc-1a000ab0a0a0"]
}
```
Signed-off-by: Darren Murray darren.murray@lacework.net
=> feat(resource): New lacework_resource_group_azure

lacework/provider.go
The function `String()` will detect if the lacework account is in our Frankfurt datacenter or
even an internal Lacework account.
=> fix: enable parsing internal accounts

website/docs/r/resource_group_gcp.html.markdown
Added explicit information for how to create a resource group containing a project that is not part of an organization. This also works in grouping projects across organizations or projects in orgs with projects not in orgs.
=> Updated GCP Resource Group argument reference

lacework/casting.go, lacework/casting_test.go
issue: https://lacework.atlassian.net/browse/ALLY-674
The function `castAndTransformStringSlice` was returning nil when an empty array is passed in. 
=> fix: return empty array when casting limit_by fields

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CONTRIBUTING.md, DEVELOPER_GUIDELINES.md, GNUmakefile
issue: https://lacework.atlassian.net/browse/ALLY-661
Add contributing documentation
CONTRIBUTING.md
DEVELOPER_GUIDELINES.md
ISSUE_TEMPLATE/bug_report.md
ISSUE_TEMPLATE/feature_request.md
ISSUE_TEMPLATE/pull_request_template.md
Add make help
```
❯ make help
-------------------------------------------------------------------
Lacework terraform-provider-lacework Makefile helper:
ci - *CI ONLY* Runs tests on CI pipeline
prepare - Initialize the go environment
release - *CI ONLY* Prepares a release of the Terraform provider
deps - Update dependencies provided by UPDATE_DEP argument
alldeps - Update all dependencies
go-vendor - Runs go mod tidy, vendor and verify to cleanup, copy and verify dependencies
build - Runs fmtcheck and go install
build-cross-platform - Compiles the …
```
=> docs: Add contributing documentation

examples/resource_lacework_resource_group_machine/main.tf, examples/resource_lacework_resource_group_machine/variables.tf, integration/integration.go, integration/resource_lacework_resource_group_machine_test.go, lacework/provider.go, lacework/resource_lacework_resource_group_machine.go, website/docs/r/resource_group_machine.html.markdown, website/lacework.erb
Issue: https://lacework.atlassian.net/browse/ALLY-626
New Terraform resource for managing Machine Resource Groups in Lacework
Usage:
``` hcl
resource "lacework_resource_group_machine" "machine" {
name        = "My Machine Resource Group"
description   = "This groups a subset of Machine Tags"
machine_tags {
key = "myKey"
value = "myValue"
}
}
```
Signed-off-by: Darren Murray darren.murray@lacework.net
=> feat: New Machine Resource Group Terraform Resource

examples/resource_lacework_resource_group_container/main.tf, examples/resource_lacework_resource_group_container/variables.tf, integration/integration.go, integration/resource_lacework_resource_group_container_test.go, lacework/provider.go, lacework/resource_lacework_resource_group_container.go, website/docs/r/resource_group_container.html.markdown, website/lacework.erb
Issue: https://lacework.atlassian.net/browse/ALLY-625
New Terraform resource for managing Container Resource Groups in Lacework
Usage:
``` hcl
resource "lacework_resource_group_container" "container" {
name        = "My Machine Resource Group"
description   = "This groups a subset of Machine Tags"
container_tags = ["myTag"]
container_labels {
key = "myKey"
value = "myValue"
}
}
```
Signed-off-by: Darren Murray darren.murray@lacework.net
=> feat: New Container Resource Group Terraform Resource

lacework/provider.go
***Issue***: N/A
After notifying our users and waiting for a few months, we are ready to switch over to APIv2 by default.
=> refactor: switch over to use APIv2 by default

website/docs/index.html.markdown
Signed-off-by: Robert Wedd <robert.wedd@lacework.net>
---
name: Updated documentation for using multiple aliases for SubAccounts
about: 'type(doc): Subject of the pull request '
---
Documentation was incorrect on how to use aliases for providers with sub accounts
Include any other relevant information such as how to use the new fuctionality, screenshots, etc.
=> docs: update multiple aliases for sub-accounts

website/docs/r/integration_gar.html.markdown, website/docs/r/integration_gcr.html.markdown
JIRA: https://lacework.atlassian.net/browse/ALLY-715
We should help users discover our Modules since they make it really easy to do end-to-end integrations.
=> docs: mention new GAR and GCR Modules

GNUmakefile
***Issue***: https://lacework.atlassian.net/browse/ALLY-707
This PR fixes the "known" issue with our release pipeline similar to:
https://github.com/lacework/terraform-provider-lacework/pull/202
The problem is that we were not running the vendor commands (`tidy`) to clean the `go.sum` file.
=> ci: run vendor commands after dep update

integration/resource_lacework_resource_group_account_test.go, integration/resource_lacework_resource_group_aws_test.go, integration/resource_lacework_resource_group_azure_test.go, integration/resource_lacework_resource_group_container_test.go, integration/resource_lacework_resource_group_gcp_test.go, integration/resource_lacework_resource_group_machine_test.go
***Issue***: [Include link to the Jira/Github Issue](https://lacework.atlassian.net/browse/ALLY-705)
Avoid conflicts in integration tests by setting unique names
=> test: create unique names for resource groups integration tests

integration/resource_lacework_integration_pagerduty_test.go, lacework/resource_lacework_alert_channel_pagerduty.go
PagerDuty Api has been updated to return apiIntgKey as empty string, this change removes apiIntgKey from resourceLaceworkAlertChannelPagerDutyRead and amends test assertions.
=> fix: remove apiIntgKey from resourceLaceworkAlertChannelPagerDutyRead

website/docs/r/alert_channel_aws_cloudwatch.html.markdown, website/docs/r/alert_channel_aws_s3.html.markdown
***Issue***: https://lacework.atlassian.net/browse/ALLY-778
Update AWS -> Amazon on cloudwatch & S3 resource documentation
=> docs: update 'aws' s3/cloudwatch to 'amazon' in documentation

examples/resource_lacework_policy/main.tf, integration/integration.go, integration/resource_lacework_policy_test.go, lacework/provider.go, lacework/resource_lacework_policy.go, lacework/schema_validators.go, website/docs/r/policy.html.markdown, website/lacework.erb
***Issue***: https://lacework.atlassian.net/browse/ALLY-871
Add new resource `lacework_policy`
Usage: 
```hcl
resource "lacework_policy" "example" {
title        = "My Policy"
query_id     = "LW_Global_AWS_CTA_CloudTrailChange"
severity     = "High"
type         = "Violation"
description  = "Policy Created via Terraform"
remediation  = "Please investigate"
evaluation   = "Hourly"
evaluator_id = "Cloudtrail"
enabled      = true
alerting {
enabled = false
profile = "LW_CloudTrail_Alerts"
}
}
```
=> feat: new lacework_policy resource

lacework/resource_lacework_query.go
Evaluator ID cannot be updated on an existing query
Add check to query update function to check for changes
=> fix: prevent updating evaluator_id on existing queries

examples/resource_lacework_policy/main.tf, examples/resource_lacework_query/main.tf, integration/resource_lacework_query_test.go, lacework/resource_lacework_policy.go, lacework/resource_lacework_query.go
***Issue***: N/A
We are about to release the deprecation of the field `evaluatorId` from our APIs, see https://lacework.atlassian.net/browse/RAIN-27035
This change is refactoring both, query and policy resources, to remove this `evaluator_id` field. 
We may need to update more tests. Also, I want to include a change that removes the need for
the user to enter the query id twice. For that, I need to ask around a bit more about the future
of this field from an API standpoint.
=> refactor: remove evaluator_id from policy and query resources

examples/resource_lacework_query/main.tf, integration/resource_lacework_query_test.go, website/docs/r/policy.html.markdown, website/docs/r/query.html.markdown
***Issue***: N/A
The motivation of this change it to avoid making our users set the query
id twice, it makes no sense to allow them to configure a different query
id, especially not since the platform enforces that both, the query id and
the query text match.
Furthermore, we have introduced the concept of anonymous queries, such
queries are encouraged and should the default way that users create and
manage LQL queries.
This change updates all documentation and tests to avoid adding the
query id inside the query text.
Updated integration tests and documentation.
=> refactor: encourage the use of anonymous queries

integration/rollback_alert_channel_test.go
***Issue***: https://lacework.atlassian.net/browse/RAIN-28525
Our APIs sometimes return the full `/test` payload from the underlying system we are testing
the alert against, but some other times the APIs only return a 500 Internal Server Error.
We are disabling our Terraform tests for now but I think our responses should be consistent. 
This should give better stability to our automated CI integration tests.
=> chore: comment out error check in rollback test

examples/resource_lacework_integration_ecr/iam_role/main.tf, examples/resource_lacework_integration_ecr/iam_role/variables.tf, integration/resource_lacework_integration_ecr_test.go, integration/resource_lacework_query_test.go, lacework/resource_lacework_integration_ecr.go
***Issue***: https://github.com/lacework/terraform-provider-lacework/issues/270
https://lacework.atlassian.net/browse/ALLY-889
Add validation to ecr 'limit_num_imgs', which can only be 5, 10 ,15
Added test `TestIntegrationECRNumImagesValidation`
=> feat: add validation to ecr 'limit_num_imgs'

examples/data_source_lacework_agent_access_token/main.tf, examples/resource_lacework_agent_access_token/main.tf, integration/resource_lacework_agent_access_token_test.go, lacework/data_source_lacework_agent_access_token.go
***Issue***:  https://lacework.atlassian.net/browse/ALLY-921
dataSourceLaceworkAgentAccessTokenRead retrieved tokens using `v1/external/tokens` change this request to use `v2/AgentAccessTokens`
=> fix: migrate agent access token data source to use v2 api

examples/resource_lacework_policy/main.tf, integration/resource_lacework_policy_test.go, lacework/resource_lacework_policy.go, website/docs/r/policy.html.markdown
***Issue***: 
https://lacework.atlassian.net/browse/ALLY-988
Add `tags` field to policy resource
Add computed field `generated_tags` to policy resource
Some policy tags will be automatically added by the server, to prevent tf state diff issues there are 2 fields for tags. User provided tags, in the `tags` field. And a computed field `generated_tags`
=> feat: add tags field to policy resource

website/docs/r/report_rule.html.markdown
fixed a typo - i believe it's meant to be `lacework_alert_channel_email` rather than `lacework_report_channel_email` since that resource type does not exist.
=> docs: update report_rule.html.markdown

examples/resource_lacework_vulnerability_exception_host/main.tf, integration/resource_lacework_vulnerability_exception_container_test.go, integration/resource_lacework_vulnerability_exception_host_test.go, lacework/resource_lacework_vulnerability_exception_container.go, lacework/resource_lacework_vulnerability_exception_host.go
***Issue***:  https://lacework.atlassian.net/browse/ALLY-1055
- Check for empty string before attempting to parse expiry
- Add  integration test with no expiry field
=> fix: time parse error for expiry field

website/docs/index.html.markdown
***Issue***: https://lacework.atlassian.net/browse/ALLY-1083
I forgot to add the new `api_token` to the argument reference.
The registry will get updated: https://registry.terraform.io/providers/lacework/lacework/latest/docs#argument-reference
=> docs: adds api_token to argument reference

lacework/resource_lacework_integration_gcp_at.go
***Issue***: 
https://lacework.atlassian.net/browse/ALLY-1139
Refactor gcp_at resource to use v2 api
=> refactor: migrate gcp_at to use v2 api

lacework/resource_lacework_integration_azure_cfg.go
***Issue***:
https://lacework.atlassian.net/browse/ALLY-1135
migrate resource_lacework_integration_azure_cfg to use v2 api
=> refactor: migrate resource_lacework_integration_azure_cfg to use v2 api

lacework/resource_lacework_agent_access_token.go
***Issue***: 
https://lacework.atlassian.net/browse/ALLY-1125
migrate agent_access_token to use v2 api
=> refactor: migrate agent_access_token to use v2 api

lacework/resource_lacework_integration_gcp_at.go
***Issue***:  https://lacework.atlassian.net/browse/ALLY-1238
From v2 of the api the private key id field is a sensitive value and not returned. The diff needs to be suppressed for this field, otherwise there will be drift
=> fix: suppressdiff for gcp_at private_key_id

integration/resource_lacework_alert_profile_test.go
Fix alert profile test. Find alertTemplate assertion from returned alerts by name
=> test: change alert_profile test to read second element from alerts array

examples/resource_lacework_integration_docker_v2/main.tf, examples/resource_lacework_integration_ecr/access_key/main.tf, examples/resource_lacework_integration_ecr/iam_role/main.tf, examples/resource_lacework_integration_gcr/main.tf, integration/resource_lacework_integration_gcr_test.go, lacework/casting.go, lacework/resource_lacework_integration_docker_v2.go, lacework/resource_lacework_integration_ecr.go, lacework/resource_lacework_integration_gcr.go, website/docs/r/integration_docker_hub.html.markdown, website/docs/r/integration_docker_v2.html.markdown, website/docs/r/integration_ecr.html.markdown, website/docs/r/integration_gar.html.markdown, website/docs/r/integration_gcr.html.markdown, website/docs/r/integration_ghcr.html.markdown
***Issue***: https://lacework.atlassian.net/browse/LINK-1089
We are replacing the argument `limit_by_labels` in favor of `limit_by_label`
Why? Because users can set many labels with the same key. For example,
to limit by the label `key` with values `value` and `value2`, plus the label `key1` with value `value`.
```hcl
limit_by_label {
key   = "key"
value = "value"
}
limit_by_label {
key   = "key"
value = "value2"
}
limit_by_label {
key   = "key1"
value = "value"
}
```
=> fix: all container registry integrations 🐛 

website/docs/r/alert_rule.html.markdown
Include `K8sActivity` event category type in alert_rule docs
=> docs: include K8sActivity event category type in alert_rule docs

examples/resource_lacework_policy/main.tf, integration/resource_lacework_policy_test.go, website/docs/r/policy.html.markdown
***Issue***: N/A - Saw it on our CI pipeline
CI is failing with:
```
│ Error:                                                                                                                                                                                                                                           
│   [POST] https://customerdemo.lacework.net/api/v2/Policies                                                                                                                                                                                       
│   [400] [Error: tag key: domain is reserved, Error: tag key: subdomain is reserved] …
```
=> ci: fix new policy tag restrictions

integration/resource_lacework_team_member_test.go
***Issue***: https://lacework.atlassian.net/browse/GROW-1351
We upgraded our Test Lacework Account to the new RBAC model where we do not support Team Members. CI is failing so, we are just disabling the tests for now.
We will come back to this once we have a replacement.
=> ci: disable Team Member integration tests

examples/resource_lacework_alert_rule/main.tf, integration/resource_lacework_alert_rule_test.go, lacework/resource_lacework_alert_rule.go
***Issue***: https://lacework.atlassian.net/browse/GROW-1373
- Change `event_categories` to TypeSet so Terraform will ignore the ordering in a diff.
- Reenable AlertRule tests `TestAlertRuleCreate`
=> fix: alert-rule 'event categories' drift

website/docs/r/agent_access_token.html.markdown
https://lacework.atlassian.net/jira/software/projects/GROW/boards/58?selectedIssue=GROW-1434
Add missing field `enabled` from `agent_access_token` resource
=> docs: add 'enabled' to agent_access_token doc

go.sum, website/docs/r/integration_aws_agentless_scanning.html.markdown, website/docs/r/integration_aws_org_agentless_scanning.html.markdown, website/docs/r/integration_gcp_agentless_scanning.html.markdown
***Issue***: https://lacework.atlassian.net/browse/RAIN-54831 
This is a follow up to https://github.com/lacework/terraform-provider-lacework/pull/484#pullrequestreview-1515286361 to add documentation updates added in that PR.
I've also committed the result of `make go-vendor` in e84fff5f3c2456bdc29d2c8fcc8e222c7bc3c525 in response to a slack sidebar: https://lacework.slack.com/archives/C03H3863SQG/p1688587897383779
=> docs(website): add multivolume and stopped instance arguments

website/docs/r/integration_oci_cfg.html.markdown, website/lacework.erb
***Issue***: [SPM-765](https://lacework.atlassian.net/browse/SPM-765)
Add documentation for the OCI config resource.
The actual logic was added in #498. 
[SPM-765]: https://lacework.atlassian.net/browse/SPM-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add documentation for the OCI config integration

examples/resource_lacework_managed_policies/main.tf, integration/integration.go, integration/resource_lacework_managed_policies_test.go, lacework/provider.go, lacework/resource_lacework_managed_policies.go, website/docs/r/managed_policies.html.markdown
Create a new resource `lacework_managed_policies` to manage the state (enable/disable) and the severity of Lacework defined policies (policies that start with `lacework-global`)
```hcl
resource "lacework_managed_policies" "example" {
policy {
id       = "lacework-global-1"
enabled  = true
severity = "High"
}
policy {
id       = "lacework-global-2"
enabled  = true
severity = "Critical"
}
policy {
id       = "lacework-global-10"
enabled  = false
}
}
```
The following arguments are supported:
* `id` - (Required) The Lacework defined policy id.
* `enabled` - (Required) Whether the policy is enabled or disabled.
* `severity` - (Optional) The list of the severities. Valid severities include:
`Critical`, `High`, `Medium`, `Low` and `Info`.
Run `make integration-test regex=TestManagedPolicies` to …
=> feat: add new lacework_managed_policies resource

lacework/resource_lacework_integration_gcp_agentless_scanning.go
**Summary**
Terraform update for https://github.com/lacework/terraform-gcp-agentless-scanning fails as the private key id is empty.
On investigating with @afiune , we found that the patch workflow sends empty key instead of omitting it from the request.
**How did you test this change?**
Update the terraform provider with the go-sdk changes (https://github.com/lacework/go-sdk/pull/1352) and pointed terraform module to use the provider. Terraform update went through successfully,
**Issue**
https://lacework.atlassian.net/browse/LINK-1923
=> fix: do not update private key id on read

lacework/resource_lacework_integration_gcp_agentless_scanning.go
***Issue***: 
Those were noticed while I was referring to GCP lacework provider for Azure.
1. `resource_id` should be the id, not integration id. resource_id should be [either a project id or an org id](https://github.com/lacework/terraform-provider-lacework/blame/main/lacework/resource_lacework_integration_gcp_agentless_scanning.go#L124-L127), whereas the intgGuid is [the common integration id](https://github.com/lacework/terraform-provider-lacework/blame/main/lacework/resource_lacework_integration_gcp_agentless_scanning.go#L32-L35)
2. the setID("") was not needed
Test w/ the integration test.
=> fix: resource_id and empty id in agentless GCP

.github/workflows/nightly.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml, .github/workflows/test-build.yml, .github/workflows/verify-release.yml
***Issue***: 
https://lacework.atlassian.net/browse/GROW-2760
These are initial versions of the workflows to replace codefresh. These are likely not final but I need some version of these in main to be able to execute them in my branch. These are currently set to manual execution only.
=> ci: add initial github workflows to replace codefresh

.github/workflows/prepare-release.yml, .github/workflows/release.yml, .github/workflows/test-build.yml
***Issue***: 
https://lacework.atlassian.net/browse/GROW-2760
Some of the github workflows have the incorrect commands for that workflow.
=> ci: fix swapped release commands in release workflows

.github/workflows/test-build.yml
***Issue***: 
https://lacework.atlassian.net/browse/GROW-2760
Sudo command missing from apt-get install causing failure
=> ci: add sudo to apt-get install command

docs/integration_azure_ad_al.md, docs/resources/integration_azure_ad_al.md, examples/resource_lacework_integration_azure_ad_al/main.tf, integration/integration.go, integration/resource_lacework_integration_azure_ad_al_test.go, lacework/provider.go, lacework/resource_lacework_integration_azure_ad_al.go
***Issue***: https://lacework.atlassian.net/browse/RAIN-92781
Add support for AzureAdAl integration terraform module
**Tests performed**
```
make prepare
make build
make install
```
```
cd resource_lacework_integration_azure_ad_al
terraform init
```
```
(⎈|lacework.teleport.sh-lacework-devtest-dev3:N/A)➜  resource_lacework_integration_azure_ad_al git:(RAIN-92781-azure-ad-al) ✗ terraform apply
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "lacework_integration_azure_ad_al" "example" {
+ created_or_updated_by   = (known after apply)
+ created_or_updated_time = (known after apply)
+ enabled …
```
=> feat(RAIN-92781): Add provider for AzureAdAl integration

docs/resources/policy.md
When creating a new policy, the suffix, if specified, is sent as `PolicyId` field to the API. This applies constraints to the ID that are not reflected in the docs and can't be easily deduced from the name of the attribute. This leads to debugging 400 API errors.
After having read the documentation I had 3 attempts to run `terraform apply` before I figured out what was expected. The error messages from the API were not helpful as they refer to the field as `PolicyId` which it was not.
`policy_id_suffix = "-tenant"` causes:
```text
│ Error: 
│   [POST] https://tenant.lacework.net/api/v2/Policies
│   [400] Error: unable to create policy using policyId '-tenant'. Supported format for policyId is '<policy identifier>' all lowercase up to 16 characters, followed by optional '-<numeric …
```
=> docs(policy): Reflect API constraints in policy suffix docs

lacework/resource_lacework_query.go
***Issue***: https://lacework.atlassian.net/browse/LINK-3033
The issue is when importing lacework_resource_query, the `query_id` is not set which causes a state drift. This PR fixes it.
=> fix(LINK-3033): set query_id when importing lacework_resource_query

docs/resources/convert_v1_to_v2_resource_groups.md, docs/resources/resource_group.md, integration/resource_lacework_alert_rule_test.go
***Issue***: https://lacework.atlassian.net/browse/CAD-822
This is the doc for detailing how to convert the V1 to V2 resource groups
***Test:***
New terraform V2 resource groups created successfully in qan environment.
=> chore(CAD-828): create the v1 to v2 resource group conversion doc

docs/resources/policy_compliance.md
***Issue***:
https://lacework.atlassian.net/browse/LINK-3391
tag with key `domain` and `subdomain` are restricted since this change about 2 years ago https://lacework.atlassian.net/browse/RAIN-45251 but terraform documentation was never updated. 
=> fix(LINK-3391): Update policy_compliance.md

docs/resources/alert_channel_microsoft_teams.md, examples/resource_lacework_alert_channel_microsoft_teams/main.tf, integration/resource_lacework_alert_channel_microsoft_teams_test.go, integration/rollback_alert_channel_test.go
- Use correct Microsoft teams webhook URL in tests
- The teams webhook URL pattern was updated in https://github.com/lacework/services/commit/a9c98f1e8d2bbdbe5aa5fd3219bbecb2d0bc4aaf#diff-89e41363d2430e8f79e5c54d90c7f8266b1ed4bc8cafe7e2b2a9c11773c88712R3406
=> fix: use correct Microsoft teams webhook URL in tests

docs/resources/integration_azure_al.md
***Issue***: 
https://lacework.atlassian.net/browse/CAD-1604
Customer  discovered a typo in TF docs here:
[Terraform Registry](https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_azure_al) 
In the resource "lacework_integration_azure_at" "account_abc" {
It should not be  "at" in the end It should be "al"
=> chore: typo change from 'at' to 'al'
